### ISSUE TITLE
unable to use elan-init.sh

### ISSUE THREAD

**Issue by konradvoelkel** [Kha/elan#10]
With both the suggested
curl https://raw.githubusercontent.com/Kha/elan/master/elan-init.sh -sSf | sh
as well as running elan-init.sh directly from the cloned git repo I run into this:
```
info: downloading installer
curl: (22) The requested URL returned error: 404 Not Found
elan: command failed: curl -sSfL https://github.com/Kha/elan/releases/download/v0.6.1/elan-i686-unknown-linux-gnu.tar.gz -o /tmp/tmp.gEvE9O5U2v/elan-init.tar.gz
```
I tried to use the 0.6.1 binary "elan-x86_64-unknown-linux-gnu.tar", which seems to contain a single file "elan-init", but there is a problem (I am on a 32-bit Ubuntu and it is a 64-bit ELF).

My issue is: I was unable to simply compile the binary "elan-init" myself (or, if there is no compiling to be done because ruby is interpreted, I failed to install elan after all).

I guess this can be solved by documenting how to achieve this. Maybe a fix for elan-init.sh is also possible, but I can understand that no 32-bit binaries are distributed.

**Comment by Kha** [comment]
Hi,

elan only supports the platforms for which there are official Lean releases - downloading those is its main purpose after all. With Ubuntu and most other distributions having dropped support for i686, I don't see us adding support for it.

On unsupported platforms, I'd suggest compiling Lean directly from source without using elan.
