### ISSUE TITLE
Dealing with the broken `leanpkg.bat`

### ISSUE THREAD

**Issue by solson** [Kha/elan#16]
I made [a PR to Lean](https://github.com/leanprover/lean/pull/1976) fixing `leanpkg.bat`'s handling of spaces in paths, but as this is unlikely to make it into a release and wouldn't solve the problem when using older versions, it might make sense to solve the problem in elan.

Two approaches have been suggested:
1. Have elan automatically patch `leanpkg.bat` after downloading a new Lean version
2. Have elan avoid `leanpkg.bat` entirely and directly invoke `lean` with the `--run <path to leanpkg main.lean>` arguments and the right environment variables

Lately a number of users have installed elan on Windows systems where they have spaces in their usernames and come to the Zulip with this problem.

**Comment by rwbarton** [comment]
Where does elan get its downloads from? Perhaps a third option is for elan to download Lean distributions which have already been patched?

**Comment by rwbarton** [comment]
Lean 3.4.2 was released with a fixed `leanpkg.bat`, so maybe we can just close this.
