### ISSUE TITLE
Lean for mac requires brew install gmp

### ISSUE THREAD

**Issue by aqjune** [Kha/elan#19]
I found that running lean after `curl https://raw.githubusercontent.com/Kha/elan/master/elan-init.sh -sSf` in Mac raises `dyld: Library not loaded: /usr/local/opt/gmp/lib/libgmp.10.dylib` error.

This can be resolved by installing gmp via brew (`brew install gmp`).

**Comment by bryangingechen** [comment]
This is mentioned in the [Prerequisites](https://github.com/Kha/elan#prerequisites) section of the readme.

**Comment by aqjune** [comment]
Oh, I missed that section, sorry. :)
