### ISSUE TITLE
improve elan-init's version detection

### ISSUE THREAD

**Issue by haraldschilly** [Kha/elan#21]
right now, the elan-init.sh file does this: `_latest=$(ensure curl -sSf "$ELAN_UPDATE_ROOT/latest" | cut -d'"' -f2 | awk -F/ '{print $NF}')` which relies on github never changing a redirection page with that content: `<html><body>You are being <a href="https://github.com/Kha/elan/releases/tag/v0.7.5">redirected</a>.</body></html>`

A more robust way might be to query the github api directly for the latest urls of all downloads and filter them? 

e.g. `curl -s https://api.github.com/repos/Kha/elan/releases/latest | jq -r '.assets | .[] | select(.name|test(".*-linux-.*")) | .browser_download_url'`

or just a drop-in replacement: 

```
$ curl -s https://api.github.com/repos/Kha/elan/releases/latest | jq -r '.tag_name'
v0.7.5
```

**Comment by Kha** [comment]
We cannot use Github's API because of rate limits, nor should we assume the presence of `jq`.
