### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by cipher1024** [Kha/elan#5]
it would be great to know how the normal workflow based on `leanpkg` changes when moving to `elan`. More specifically, I'd like to know what becomes automatic and what tasks change. I'd like to see:
   * [ ] when switching from one Lean project to another, how do we activate the right Lean version
   * [ ] in a `leanpkg` project how do we upgrade the Lean version
   * [ ] when upgrading dependencies, how do we match the version of Lean required by the dependencies, the one required by the project and the one that is installed

**Comment by Kha** [comment]
This is/should probably be handled by `leanproject` now
